name: breakout
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  provider: ^6.1.2
  flame: ^1.18.0
  forge2d: ^0.13.0
  flame_forge2d: ^0.18.1
  audioplayers: ^6.0.0
  sensors: ^2.0.3
  sensors_plus: ^5.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/breakout_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/audio/menu_music.mp3
    - assets/audio/play_music.mp3
    - assets/audio/settings_music.mp3
    - assets/audio/play_button.mp3
    - assets/audio/slider_sound.mp3
  uses-material-design: true